// listShopping
export const shoppingIcon1 = require("../../assets/app/shopping/shopping-icon1.png")
export const shoppingIcon2 = require("../../assets/app/shopping/shopping-icon3.png")
export const shoppingIcon3 = require("../../assets/app/shopping/shopping-icon5.png")
export const shoppingIcon4 = require("../../assets/app/shopping/shopping-icon4.png")
export const shoppingIcon5 = require("../../assets/app/shopping/shopping-icon2.png")
export const shoppingIcon6 = require("../../assets/app/shopping/shopping-icon6.png")
export const shoppingIcon7 = require("../../assets/app/shopping/shopping-icon7.png")
export const shoppingIcon8 = require("../../assets/app/shopping/shopping-icon8.png")

// group
export const groupIcon1 = require("../../assets/app/group/group-icon1.png")
export const groupIcon2 = require("../../assets/app/group/group-icon2.png")
export const groupIcon3 = require("../../assets/app/group/group-icon3.png")
export const groupIcon4 = require("../../assets/app/group/group-icon4.png")
export const createGroup1 = require("../../assets/app/group/create-group1.png")
export const createGroup2 = require("../../assets/app/group/create-group2.png")
export const joinGroup1 = require("../../assets/app/group/join-group1.png")
export const joinGroup2 = require("../../assets/app/group/join-group2.png")
export const shoppingListIcon = require("../../assets/app/group/shopping-list-icon.png")
export const fridgeIcon = require("../../assets/app/group/fridge-icon.png")
export const menuIcon = require("../../assets/app/group/menu-icon.png")
export const reportIcon = require("../../assets/app/group/report-icon.png")
export const userListIcon = require("../../assets/app/group/user-list-icon.png")
export const mealIcon1 = require("../../assets/app/group/meal-icon1.png")
export const mealIcon2 = require("../../assets/app/group/meal-icon2.png")
export const mealIcon3 = require("../../assets/app/group/meal-icon3.png")
export const mealIcon4 = require("../../assets/app/group/meal-icon4.png")

// common
export const editIcon = require("../../assets/app/common/edit-icon.png")
export const deleteIcon = require("../../assets/app/common/delete-icon.png")
export const addToCartIcon = require("../../assets/app/shopping/add-to-cart-icon.png")
export const addToCartIcon2 = require("../../assets/app/shopping/add-to-cart-icon2.png")
export const addIcon = require("../../assets/app/common/add-icon.png")
export const filterIcon = require("../../assets/app/common/filter-icon.png")
export const backIcon = require("../../assets/app/common/arrow-left-2.png")
export const createIcon = require("../../assets/app/common/create.png")
export const goBackIcon = require("../../assets/app/common/go-back-icon.png")
export const clearIcon = require("../../assets/app/common/clear.png")
export const isCheckedIcon = require("../../assets/app/common/is-checked-icon.png")
export const plusIcon = require("../../assets/app/common/plus-icon.png")
export const minusIcon = require("../../assets/app/common/minus-icon.png")
export const floatingButton = require("../../assets/app/common/floating-button.png")
export const notesIcon = require("../../assets/app/common/notes-icon.png")
export const defaultAvatar = require("../../assets/app/common/default-avatar.png")
